name: Create Branch Workflow

on:
  workflow_dispatch:
    inputs:
      branch-type:
        description: 'Type of branch (feature, bugfix, etc.)'
        required: true
        default: 'feature'
      branch-name:
        description: 'Name of the branch'
        required: true
        default: 'example-branch'

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create new branch
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-type: ${{ github.event.inputs.branch-type }}
          branch-name: ${{ github.event.inputs.branch-name }}
